<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bin</string>
		<string>machine</string>
	</array>
	<key>name</key>
	<string>Calcutron-33 Machinecode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>entity.name.function.cutronbin</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cutronbin</string>
	<key>uuid</key>
	<string>389248E5-C337-4E7E-B4E0-2F88516DF858</string>
</dict>
</plist>
